# Generated by Django 4.2 on 2024-11-10 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datetime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('datetime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employees.datetime')),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_az', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
            bases=('employees.datetime',),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('datetime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employees.datetime')),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_az', models.CharField(max_length=200, null=True)),
                ('salary', models.IntegerField()),
                ('department_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
            bases=('employees.datetime',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('datetime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employees.datetime')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Retired', 'Retired'), ('Leave of Absence', 'Leave of Absence'), ('Fəal', 'Fəal'), ('İşləmir', 'İşləmir'), ('Məzuniyyətə çıxıb', 'Məzuniyyətə çıxıb')], max_length=200, null=True)),
                ('status_en', models.CharField(blank=True, choices=[('Active', 'Active'), ('Retired', 'Retired'), ('Leave of Absence', 'Leave of Absence'), ('Fəal', 'Fəal'), ('İşləmir', 'İşləmir'), ('Məzuniyyətə çıxıb', 'Məzuniyyətə çıxıb')], max_length=200, null=True)),
                ('status_az', models.CharField(blank=True, choices=[('Active', 'Active'), ('Retired', 'Retired'), ('Leave of Absence', 'Leave of Absence'), ('Fəal', 'Fəal'), ('İşləmir', 'İşləmir'), ('Məzuniyyətə çıxıb', 'Məzuniyyətə çıxıb')], max_length=200, null=True)),
                ('department_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department')),
                ('position_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.position')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
            bases=('employees.datetime',),
        ),
    ]
